// Finalize TypeDoc output into a single, committed docs/api.md.
// TypeDoc (modules strategy, single entry point) emits one file in a temp dir;
// we prepend a "generated" banner, move it to docs/api.md, and clean up.
import { readFileSync, writeFileSync, rmSync } from "node:fs";

const tmp = "docs/.api-tmp/README.md";
const dest = "docs/api.md";
const banner =
  "<!-- Generated by `bun run docs` (TypeDoc) from the source TSDoc + types. Do not edit by hand. -->\n\n";

// Hand-written section appended to the generated reference. These six symbols are
// re-exported from `src/index.ts` but dropped by TypeDoc's `excludeExternals`
// (they live in the untyped `@liamcottle/meshcore.js`), so they must be documented here
// to keep the reference complete.
const transportsSection = `## Transports & raw access

These symbols are re-exported as-is from the untyped \`@liamcottle/meshcore.js\`, so they carry minimal or no type information here. Most users should not need them directly — prefer the typed helpers \`MeshCoreClient.tcp(host, port)\` and \`MeshCoreClient.serial(path)\` to create a client.

- \`TCPConnection\` — \`new TCPConnection(host: string, port: number)\`; the WiFi transport.
- \`NodeJSSerialConnection\` — \`new NodeJSSerialConnection(path: string)\`; the USB-serial transport.
- \`Connection\` — the base connection class; the type of \`MeshCoreClient.raw\` (escape hatch for unwrapped APIs).
- \`Constants\` — the raw numeric protocol constants from meshcore.js.
- \`BufferUtils\`, \`TransportKeyUtil\` — raw helper utilities from meshcore.js.

See the [Guide](./guide.md) for connecting.
`;

const generated = readFileSync(tmp, "utf8");
writeFileSync(dest, banner + generated + "\n\n" + transportsSection);
rmSync("docs/.api-tmp", { recursive: true, force: true });
console.log(`Wrote ${dest}`);
