// Finalize TypeDoc output into a single, committed docs/api.md.
// TypeDoc (modules strategy, single entry point) emits one file in a temp dir;
// we prepend a "generated" banner, move it to docs/api.md, and clean up.
import { readFileSync, writeFileSync, rmSync } from "node:fs";

const tmp = "docs/.api-tmp/README.md";
const dest = "docs/api.md";
const banner =
  "<!-- Generated by `bun run docs` (TypeDoc) from the source TSDoc + types. Do not edit by hand. -->\n\n";

writeFileSync(dest, banner + readFileSync(tmp, "utf8"));
rmSync("docs/.api-tmp", { recursive: true, force: true });
console.log(`Wrote ${dest}`);
